application.project.security.provider.admin:
    resource: '@ApplicationProjectSecurityAdminBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.security.provider.api:
    resource: '@ApplicationProjectSecurityUserBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.content:
    resource: '@ApplicationProjectContentBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.media:
    resource: '@ApplicationProjectMediaBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.setting:
    resource: '@ApplicationProjectSettingBundle/Resources/config/routes/routes.yaml'
    prefix: /

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#api_login_check:
#    path: /api/login_check

app.swagger_ui:
    path: /api
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

###############################################################################
# Schema Bundles Routes
###############################################################################

application.internit.empreendimentobundle:
    resource: '@ApplicationInternitEmpreendimentoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.acompanhamentobundle:
    resource: '@ApplicationInternitAcompanhamentoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.bannerbundle:
    resource: '@ApplicationInternitBannerBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.statusbundle:
    resource: '@ApplicationInternitStatusBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.tagbundle:
    resource: '@ApplicationInternitTagBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.corretoronlinebundle:
    resource: '@ApplicationInternitCorretorOnlineBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.realizacaobundle:
    resource: '@ApplicationInternitRealizacaoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.tipobundle:
    resource: '@ApplicationInternitTipoBundle/Resources/config/routes/routes.yaml'
    prefix: /

