# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'pt_BR'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # overload kernel exception
    #    App\Application\Project\ContentBundle\EventListener\ExceptionListener:
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception }

    #    App\Application\Project\SecurityProviderApiBundle\EventListener\ExceptionListener:
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    #
    #


    # ####################################################################################
    # injeções de dependências

    #    app.menu_listener:
    #        class: App\Application\Project\ContentBundle\EventListener\MenuBuilderListener
    #        tags:
    #            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
    #        arguments:


    #    admin.custom:
    #        class: App\Admin\CustomAdmin
    #        tags:
    #            - { name: sonata.admin, model_class: App\Entity\Custom, manager_type: orm, label: Category, security_handler: App\Application\Project\AdminBundle\Security\Handler }


    # ####################################################################################
    # serviços padrões da estrutura do projeto

    # Content Bundle
    project.content.content:
        class: App\Application\Project\ContentBundle\Admin\ContentAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\ContentBundle\Entity\Content,
                controller: App\Application\Project\ContentBundle\Controller\ContentAdminController,
                show_in_dashboard: false,
                on_top: false,
                group: "Content",
                label: Content,
                icon: 'fa fa-solid fa-passport',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }

    project.content.setting:
        class: App\Application\Project\SettingBundle\Admin\SmtpEmailAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SettingBundle\Entity\SmtpEmail,
                controller: App\Application\Project\SettingBundle\Controller\SmtpEmailAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Configurações",
                label: SMTP,
                icon: 'fas fa-cogs',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }






    # ####################################################################################
    # Provedor de usuário ADMIN

    project.security.provider.admin.user:
        class: App\Application\Project\SecurityAdminBundle\Admin\UserAdminAdmin
        calls:
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityAdminBundle\Entity\UserAdmin,
                controller: App\Application\Project\SecurityAdminBundle\Controller\UserAdminAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Admin",
                label: Administradores,
                icon: 'fa fa-solid fa-shield-alt',
            }

    project.security.provider.admin.group:
        class: App\Application\Project\SecurityAdminBundle\Admin\GroupAdminAdmin
        calls:
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityAdminBundle\Entity\GroupAdmin,
                controller: App\Application\Project\SecurityAdminBundle\Controller\GroupAdminAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Admin",
                label: Grupos,
                icon: 'fa fa-solid fa-shield-alt',
            }

    # ####################################################################################
    # Provedor de usuário API

    project.security.provider.api.user:
        class: App\Application\Project\SecurityUserBundle\Admin\UserAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityUserBundle\Entity\User,
                controller: App\Application\Project\SecurityUserBundle\Controller\UserAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Usuários",
                label: Usuários,
                icon: 'fa fa-solid fa-users',
            }

    project.security.provider.api.group:
        class: App\Application\Project\SecurityUserBundle\Admin\GroupAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityUserBundle\Entity\Group,
                controller: App\Application\Project\SecurityUserBundle\Controller\GroupAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Usuários",
                label: Grupos,
                icon: 'fa fa-solid fa-users',
            }

    # ####################################################################################
    # por favor, note que as últimas definições sao da estrutura padrão do projeto
    # adicione mais definições de serviço quando for necessária abaixo


    # Services Schemas Bundle
    # ####################################################################################
    internit.empreendimentobundle.empreendimento:
        class: App\Application\Internit\EmpreendimentoBundle\Admin\EmpreendimentoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\EmpreendimentoBundle\Entity\Empreendimento,
                controller: App\Application\Internit\EmpreendimentoBundle\Controller\EmpreendimentoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Empreendimento",
                label: Empreendimento,
                icon: 'fa fa-solid fa-book',
            }

    internit.acompanhamentobundle.acompanhamento:
        class: App\Application\Internit\AcompanhamentoBundle\Admin\AcompanhamentoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\AcompanhamentoBundle\Entity\Acompanhamento,
                controller: App\Application\Internit\AcompanhamentoBundle\Controller\AcompanhamentoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Acompanhamento",
                label: Acompanhamento,
                icon: 'fa fa-solid fa-book',
            }

    internit.bannerbundle.banner:
        class: App\Application\Internit\BannerBundle\Admin\BannerAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\BannerBundle\Entity\Banner,
                controller: App\Application\Internit\BannerBundle\Controller\BannerAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Banner",
                label: Banner,
                icon: 'fa fa-solid fa-book',
            }

    internit.statusbundle.status:
        class: App\Application\Internit\StatusBundle\Admin\StatusAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\StatusBundle\Entity\Status,
                controller: App\Application\Internit\StatusBundle\Controller\StatusAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Status",
                label: Status,
                icon: 'fa fa-solid fa-book',
            }

    internit.tagbundle.tag:
        class: App\Application\Internit\TagBundle\Admin\TagAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\TagBundle\Entity\Tag,
                controller: App\Application\Internit\TagBundle\Controller\TagAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Tag",
                label: Tag,
                icon: 'fa fa-solid fa-book',
            }

    internit.corretoronlinebundle.corretoronline:
        class: App\Application\Internit\CorretorOnlineBundle\Admin\CorretorOnlineAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\CorretorOnlineBundle\Entity\CorretorOnline,
                controller: App\Application\Internit\CorretorOnlineBundle\Controller\CorretorOnlineAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "CorretorOnline",
                label: CorretorOnline,
                icon: 'fa fa-solid fa-book',
            }

    internit.realizacaobundle.realizacao:
        class: App\Application\Internit\RealizacaoBundle\Admin\RealizacaoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\RealizacaoBundle\Entity\Realizacao,
                controller: App\Application\Internit\RealizacaoBundle\Controller\RealizacaoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Realizacao",
                label: Realizacao,
                icon: 'fa fa-solid fa-book',
            }

    internit.tipobundle.tipo:
        class: App\Application\Internit\TipoBundle\Admin\TipoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\TipoBundle\Entity\Tipo,
                controller: App\Application\Internit\TipoBundle\Controller\TipoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Tipo",
                label: Tipo,
                icon: 'fa fa-solid fa-book',
            }

